### ISSUE TITLE
VAC question

### ISSUE THREAD

**Issue by Lito7** [namazso/nSkinz#120]
I'have been using the nskinz for maybe one week, i wonder what is the best way to use it without triggering a vac ban, or is it possible to get a vacation with nSkinz?

**Comment by Jeimy041** [comment]
Yes, it is possible to go on VACation with this, but you can reduce the risk to almost 0 by adding junk code to the source code, using an own injector "I recommend a manual mapping one", and protecting both the dll and the injector with VMProtect, this last one is important because you may get VAC errors if you dont VMProtect it.

**Comment by mendax47** [comment]
@Jeimy041 Can you give me any good undetectable injector..?

**Comment by melodii** [comment]
Just code one yourself

**Comment by Jeimy041** [comment]
@mendax47 I personally use RandoInjector + VMProtection for it try it by yourself

**Comment by namazso** [comment]
of course it is like with anything else injected.
that being said, nSkinz is developed to avoid the generic VAC detections.
avoiding targeted detections like signatures is not in the scope of the project.
