### ISSUE TITLE
Hey could you revamp this please it's kindof messy imo

### ISSUE THREAD

**Issue by eue398** [namazso/nSkinz#19]
revamp // recode

**Comment by wi1h** [comment]
it's relatively clean honestly. just because it doesn't fit your coding
style doesn't mean it's wrong lmao

**Comment by eue398** [comment]
butt me seen the coder say its messy

**Comment by namazso** [comment]
well, there are certain issues i know of but cba to clean up. one is the possible race condition with the configs, which should be pretty obvious to anyone reading the source. The other is the slowness of updating the vector index from the skin id. These require two special containers (preferably a static memory backed lockfree concurrent vector, and a multi-indexed map). imo implementing these, or pulling in a boost dependency which has these both would be kinda overkill for a project of this size, so i just leave these in, since they rarely cause problems.

**Comment by terryadavis** [comment]
It's not that messy I don't like how @namazso put all of their hooks in separate files instead of a manager and a bunch of utility files being separate.

**Comment by wi1h** [comment]
that's just personal preference. i like it that way tbh

**Comment by noxipoop** [comment]
hey for some reason it keeps giving me 11 errors then it gives me 37 errors and i cant compile it :( im using visual studio 2017 and is there a way to keep it undetected forever such as adding junk code?

**Comment by terryadavis** [comment]
This is not where to report and it's common sense you need to download the dependencies ImGui & JSON the replace the ones in msvs's filter and change up the include directory?

**Comment by namazso** [comment]
@terryadavis you dont even need to do any of that in fact. The paths are configured to be relative by default, and since imgui and json are submodules they get automatically cloned with --recursive
