### ISSUE TITLE
Only reading first "paint_kits" key.

### ISSUE THREAD

**Issue by wi1h** [namazso/nSkinz#4]
Turns out that for the new skins, Valve added them in a different "paint_kits" subkey (why they would do this is beyond me, but whatever). It appears the vdf parser doesn't have the functionality to handle this. Any ideas?

I've managed to get around this by making my own items_game.txt, with the two "paint_kits" keys merged together and it worked fine, however this isn't future proof, as my modified items_game.txt won't update with the game.

**Comment by namazso** [comment]
I've reversed the where the actual loaded skins are stored, here is the thread on how to parse them: https://www.unknowncheats.me/forum/counterstrike-global-offensive/216372-paintkit-parser-files-proper.html (String_t is actually CUtlString). If you implement it (possibly stuff changed because update too?) I'd be happy if you sent a PR.

**Comment by wilhueb** [comment]
Yeah I saw your post. I'll take a closer look when I find some time. If I figure something out I'll submit a PR. No promises though.
